#!/bin/sh

DIR='/home/cupivan/http/_.cupivan.ru/osm/validator/parser'
NAME=$1

cd $DIR

V=`find ./ -name $1.php`
if [[ "$V" != "" ]]
then
	cd $DIR/../common
	php validate.php $V $1 $2 $3
	exit
fi

echo "Unknow validator '$1'!"
